@startuml
    title カレーライス作成
    start
    fork
    :野菜を切る;
    :フライパンに油を引いて野菜と肉を炒める;
    :フライパンに水を注ぎ煮ながら、アクを取る;
    :火を止めてカレールウを溶かし入れる;
    :再び火をつけてとろみを付ける;
    fork again
    :米を洗う;
    :水を入れる;
    :炊飯器に入れ、開始する;
    end fork
    :カレーライス]
    stop
@enduml